apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-mongo-db
  namespace: prod
spec:
  selector:
    matchLabels:
      appdb: mongodb
      role: primary
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        appdb: mongodb
        role: primary
        tier: backend
    spec:
      containers:
      - name: primary-mongodb
        image: mongo:3.3
        env:
        - name: MONGODB_DATABASE
          value: testdata
        ports:
        - containerPort: 27017
