apiVersion: v1
kind: Service
metadata:
  name: mongodb-primary
  namespace: prod
  labels:
    appdb: mongodb
    role: primary
    tier: backend
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    appdb: mongodb
    role: primary
    tier: backend
