# cat mongo-db-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondary-mongo-db
  namespace: prod
spec:
  selector:
    matchLabels:
      appdb: mongodb
      role: replica
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        appdb: mongodb
        role: replica
        tier: backend
    spec:
      containers:
      - name: replica-mongodb
        image: mongo:3.3
        env:
        - name: MONGODB_DATABASE
          value: testdata
        ports:
        - containerPort: 27017

